DFEitechCollege/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DFEitechCollege.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DFEitechCollege/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DFEitechCollege.Models;

namespace DFEitechCollege.Controllers
{
    public class StudentController : Controller
    {
        StudentGenie genie = new StudentGenie();

        public ActionResult DeleteStudent(int id = 0) //student
        {
            return View(genie.DeleteStudent(id));
        }

        [HttpPost]
        public ActionResult ListStudents()
        {
            return View(genie.ListStudents());
        }

        public ActionResult CreateStudent(string fname = "*empty", string lname = "*empty")
        {
            return View(genie.InsertStudent(fname, lname));
        }

        public ActionResult UpdateStudent(int id, string fname, string lname)
        {
            return View(genie.UpdateStudent(id, fname, lname));
        }

        [HttpPost]
        public ActionResult _ToolStudents()
        {
            return View();
        }
    }
}

DFEitechCollege/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DFEitechCollege.Models;

namespace DFEitechCollege.Controllers
{
    public class SubjectController : Controller
    {
        SubjectGenie genie = new SubjectGenie();

        public ActionResult DeleteSubject(int id=0)
        {
            return View(genie.DeleteSubject(id));
        }

        [HttpPost]
        public ActionResult ListSubjects()
        {
            return View(genie.ListSubjects());
        }

        public ActionResult CreateSubject(string name="*empty", Boolean higher=false)
        {
            return View(genie.InsertSubject(name, higher));            
        }

        public ActionResult UpdateSubject(int id, string name, Boolean higher1=false)
        {
            return View(genie.UpdateSubject(id, name, higher1));
        }

        public ActionResult _ToolSubjects()
        {
            var model = new Subject();
            return PartialView(model);
        }
    }
}

DFEitechCollege/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DFEitechCollege.Models;

namespace DFEitechCollege.Controllers
{
    public class TeacherController : Controller
    {
        TeacherGenie genie = new TeacherGenie();

        public ActionResult DeleteTeacher(int id = 0)
        {
            return View(genie.DeleteTeacher(id));
        }

        [HttpPost]
        public ActionResult ListTeachers()
        {
            return View(genie.ListTeachers());
        }

        public ActionResult CreateTeacher(string fname = "*empty", string lname = "*empty")
        {
            return View(genie.InsertTeacher(fname, lname));
        }

        public ActionResult UpdateTeacher(int id, string fname, string lname)
        {
            return View(genie.UpdateTeacher(id, fname, lname));
        }

        [HttpPost]
        public ActionResult _ToolTeachers()
        {
            return View();
        }
    }
}

DFEitechCollege/Controllers/WorkshopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DFEitechCollege.Models;

namespace DFEitechCollege.Controllers
{
    public class WorkshopController : Controller
    {
        WorkshopGenie genie = new WorkshopGenie();

        public ActionResult CreateWorkshop(int courseId, int year, int teacherId)
        {
            return View(genie.InsertWorkshop(courseId, year, teacherId));
        }

        [HttpPost]
        public ActionResult ListWorkshops()
        {
            return View(genie.ListWorkshops());
        }

        public ActionResult DeleteWorkshop(int id = 0) //potential workshop_student floater entries
        {
            return View(genie.DeleteWorkshop(id));
        }

        public ActionResult UpdateWorkshop(int workshopId=0, int courseId=0, int year=0, int teacherId=0)
        {
            if (year == 0) { year = DateTime.Now.Year; }
            return View(genie.UpdateWorkshop(workshopId, courseId, year, teacherId));
        }

        [HttpPost]
        public ActionResult _ToolWorkshops()
        {
            return View();
        }

        public ActionResult InsertWorkshopStudent(int workshopId, int studentId)
        {            
            return View(genie.InsertWorkshopStudent(workshopId, studentId));
        }
        
    }
}

DFEitechCollege/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DFEitechCollege/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DFEitechCollege/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>DFEitech</h1>
    <p class="lead">ASP.NET Business Solutions on Demand.</p>
</div>

<div class="row">
    <div class="col-md-3">
        @using (Html.BeginForm("ListSubjects", "Subject"))
            { <input type="submit" class="btn btn-default btn-lg" value="Subjects &raquo;" /> }
            <br />        
    </div>

    <div class="col-md-3">
        @using (Html.BeginForm("ListTeachers", "Teacher"))
            { <input type="submit" class="btn btn-default btn-lg" value="Teachers &raquo;" /> }
        <br />
    </div>

    <div class="col-md-3">
        @using (Html.BeginForm("ListStudents", "Student"))
            { <input type="submit" class="btn btn-default btn-lg" value="Students &raquo;" /> }
        <br />
    </div>

    <div class="col-md-3">
        @using (Html.BeginForm("ListWorkshops", "Workshop"))
            { <input type="submit" class="btn btn-default btn-lg" value="Workshops &raquo;" /> }
        <br />
    </div>
</div>